### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by corpeder** [Tonyx97/BF1-Internal#3]
im not sure if anyone is aware of this yet but i am unable to compile i get the following error

Cannot open include file: 'CommonStates.h': No such file or directory	BF1 Internal	c:\users\steammachine\downloads\bf1-internal-master\bf1 internal\stdafx.h	13

**Comment by xsibix** [comment]
You need to include (compile and change references)

[https://github.com/Microsoft/DirectXTK](https://github.com/Microsoft/DirectXTK)

and

[https://github.com/stevemk14ebr/PolyHook](https://github.com/stevemk14ebr/PolyHook)
