### ISSUE TITLE
Debug output clean up

### ISSUE THREAD

**Issue by vicch** [Tonyx97/BF1-Internal#5]
The code could use some cleaning up, to remove or comment out debugging snippets, for example: https://github.com/Tonyx97/BF1-Internal/blob/master/BF1%20Internal/DX11.cpp#L155. Or at least use relative paths instead of absolute ones.

**Comment by bestplay9384** [comment]
It's my fault. I just forgot to delete things i dod to "explore" Tony's code, and commited with this trash ;/ You can remove it, you should imho

**Comment by vicch** [comment]
OK, I'll try. Also I'm thinking if the debug output is useful, a helper class could be added to handle the output logic (file path, format etc.) and only output in "debug" build.

**Comment by bestplay9384** [comment]
@Tonyx97 had build some Debug window in ImGui, but when i tried to set debug variable to true my game was crashing in some weird situations, so i tried my own way :D
