### ISSUE TITLE
Cannot revive as medic sometimes

### ISSUE THREAD

**Issue by Sylencer90** [Tonyx97/BF1-Internal#7]
Hope it's not wrong to post it here, but sometimes the medic is unable to revice someone.

**Comment by xsibix** [comment]
`Vector3 MyHeadPos = LocalPlayer->getSoldier()->getPosition(); // Feet Position, fix for Revive Bug
									//LocalPlayer->getSoldier()->GetBonePosition(MyHeadPos, HEAD); // Creates Revive Bug`

Dirty but simple fix for the revive bug
