### ISSUE TITLE
From a java programmer thanks

### ISSUE THREAD

**Issue by teemoer** [Tonyx97/BF1-Internal#8]
Thank you very much for sharing this code in github and will update it.
I am a Chinese Java programmer, since I saw your code, let me have the motivation to learn C + +.
In any case, it is an honor to communicate with the author and thank you again for the spirit of sharing. To know that there is a minority in China.
Www.java.sx is my blog, look forward to be able to become friends with you. My skype is +86 13093834013

**Comment by Tonyx97** [comment]
I guess it's a bit late to answer haha, I'm getting active in Github now. I'm glad you got motivated with my project, I wish you luck with C++ :)
