### ISSUE TITLE
Issue when I compile the cheat

### ISSUE THREAD

**Issue by Jeimy041** [Tonyx97/BF1-Internal#9]
So I get an error telling me this: Help pls!

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'Capstone/include/capstone.h': No such file or directory	BF1 Internal c:\users\bassy´s\desktop\prueba\bf1-internal-master\bf1 internal\stdafx.h	55

**Comment by Tonyx97** [comment]
Do some research https://github.com/stevemk14ebr/PolyHook/tree/master/Capstone
